<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
	<PropertyGroup>
		<Product>Jlw.AspNetCore.Identity</Product>
		<PackageId>Jlw.Extensions.Identity.Stores</PackageId>
		<RepositoryUrl>https://github.com/JasonLWalker/Jlw.AspNetCore.Identity.git</RepositoryUrl>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageLicenseUrl></PackageLicenseUrl>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>Provided as is</PackageReleaseNotes>

		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateAssemblyInfo>True</GenerateAssemblyInfo>
		<IsPackable>True</IsPackable>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyName>$(PackageId)</AssemblyName>
		<RootNamespace>Jlw.Extensions.Identity</RootNamespace>
		<Company>Jason L. Walker</Company>
		<Authors>Jason L. Walker</Authors>
		<Description></Description>
		<Copyright>Copyright ©2012-2025 Jason L. Walker</Copyright>
		<AssemblyOriginatorKeyFile>../key.snk</AssemblyOriginatorKeyFile>
		<SignAssembly>true</SignAssembly>
		<DelaySign>false</DelaySign>
		<VersionPrefix Condition="'$(VersionPrefix)' == ''">0.0.0.1</VersionPrefix>
		<Version>$(VersionPrefix)$(VersionSuffix)</Version>
	</PropertyGroup>

	<PropertyGroup>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>portable</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jlw.Utilities.Data" Version="5.2.9362.8244" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Jlw.Extensions.Identity.Abstractions\Jlw.Extensions.Identity.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Interfaces\" />
	  <Folder Include="Models\" />
	</ItemGroup>

	<Target Name="CustomSetVersionNumberForProj" Condition=" ('$(VersionPrefix)' == '0.0.0.1') Or ('$(Version)' == '0.0.0.1-alpha') Or ('$(Version)' == '0.0.0.1-rc') " BeforeTargets="BeforeBuild">
		<Message Text="%0A========== Setting Version Number ==========" Importance="high" />
		<Exec Command="powershell $(ProjectDir)..\build-scripts\set-version-property.ps1 -versionPrefix '' -versionSuffix '-alpha' " EchoOff="true" ConsoleToMSBuild="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="Version" />
		</Exec>
		<CreateProperty Value="$(Version)">
			<Output TaskParameter="Value" PropertyName="Version" />
		</CreateProperty>
	</Target>

</Project>
