<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>aspnet-TestMvcWebApp-48FC73E4-062C-4581-81C7-33155B23E9A9</UserSecretsId>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jlw.Extensions.ModularDbClient" Version="5.2.9362.8244" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.20" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jlw.Extensions.Identity.Mock\Jlw.Extensions.Identity.Mock.csproj" />
    <ProjectReference Include="..\Jlw.Extensions.Identity.Stores\Jlw.Extensions.Identity.Stores.csproj" />
  </ItemGroup>

</Project>
